# -*- coding: utf-8 -*-
MSG = {'msg01': '請指定UltraVNC Viewer執行檔(vncviewer.exe)的路徑',
	   'msg02': '找不到VNC Viewer',
	   'msg03': '找不到已安裝的VNC Viewer, 請先安裝VNC Viewer再使用此功能',
	   'msg04': '本地端使用\n(限水規所內網域)',
	   'msg05': '遠端連線使用\n(限水利署內網域)',
	   'msg06': '申請使用權限\n(僅限署內人員申請)',
	   'msg07': '找不到水文水理分析系統',
	   'msg08': '找不到水文水理分析系統\n請先至「申請權限」網頁下載軟體',
	   'msg09': '請指定水文水理分析系統的執行路徑(qgis-ltr.bat)',
	   'msg10': 'CCHE2D使用方式',
	   'msg11': '使用者手冊',
	   'msg12': '請先安裝SRH2D Mesh Builder QGIS插件',
	   'msg13': 'SRH2D Mesh Builder插件尚未安裝\n請從關閉視窗後開啟的連結下載SRH2D Mesh Builder安裝包',
	   'msg14': '啟用MeshBuilder',
	   'msg15': '下載MeshBuilder',
	   'msg16': '下載SRH-2D TEC Viewer',
	   'msg17': '下載ImageMagick',
	   'msg18': '水文水理分析系統'}